<?php

namespace AppBundle\Repository;

use UserBundle\Entity\User;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * OfficeRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class OfficeRepository extends EntityRepository
{
    public function getFindByUserQueryBuilder(User $user) : QueryBuilder
    {
        return $this->createQueryBuilder('o')
            ->where('o.doctor = :user')
            ->setParameter(':user', $user->getId());
    }
}
